
#ifndef FEASST_MODELS_RECURSIVE_TABLE_POTENTIAL_H_
#define FEASST_MODELS_RECURSIVE_TABLE_POTENTIAL_H_

#include <memory>
#include <vector>
#include "system/include/model_two_body.h"

namespace feasst {

class RecursiveTable1D;
class Table1D;

typedef std::map<std::string, std::string> argtype;

/**
  This is an experimental and untested alternative to TablePotential which can
  have tables inside of tables (RecursiveTable).

  The RecursiveTable is generated by comparing with the output of
  MayerSampling::training_file.
  This example assumes single-site isotropic interactions, in which case the
  training file simply contains a list of squared distances and energy.

  To begin, an inner cutoff distance is obtained by finding the lowest distance
  at which the energy is less than the given parameter "hard_limit_u."
  The outer cutoff is taken from the FileParticle.

  A 1D RecursiveTable of given size is generated by linearly
  interpolating between the closest data points.

  Then all of the data is evaluated against the following criteria in order to
  iteratively insert nested tables inside the elements of the first table,

  \f$r^2|\exp(-\beta U) - \exp(-\beta U_{table})|\f$,

  where \f$U\f$ is from the data points, \f$U_{table}\f$ is linearly
  interpolated, and \f$\beta\f$ is a given parameter which determines the
  relative emphasis on accurately fitting the highest energies.
  This functional form was inspired by the 3d integration of a Mayer funciton
  to include the \f$r^2\f$ Jacobian term to appropriately weight larger
  distances.
  In addition, increased beta (low temperature) weighs the low energy
  configurations more.
  This iterative process continues until the criteria of all data points are
  less than the given "min_criteria."

  As currently implemented, the RecursiveTable has a maximum depth of one
  recursion.
  This means that "min_criteria" can be set too low and never achieved,
  at which point the user will be presented with an error.
  This happens if a data point inside of an element that has already had a
  RecursiveTable inserted is still above the "min_criteria."
 */
class RecursiveTablePotential : public ModelTwoBody {
 public:
  //@{
  /** @name Arguments
    - mayer_training_file: input file output by MayerSampling::training_file.
    - hard_limit_u: determines the inner cutoff distance (default: 100).
    - size: the size of each of the RecursiveTable s (default: 16).
    - beta: parameter which weights low energy configurations (default: 1).
    - min_criteria: iterative target minimum criteria (default: 0.03).
   */
  explicit RecursiveTablePotential(argtype args = argtype());
  explicit RecursiveTablePotential(argtype * args);

  //@}
  /** @name Public Functions
   */
  //@{

  void precompute(Configuration * config) override;
  double energy(
    const double squared_distance,
    const int type1,
    const int type2,
    const ModelParams& model_params) override;

  std::shared_ptr<Model> create(std::istream& istr) const override {
    return std::make_shared<RecursiveTablePotential>(istr); }
  std::shared_ptr<Model> create(argtype * args) const override {
    return std::make_shared<RecursiveTablePotential>(args); }
  void serialize(std::ostream& ostr) const override;
  explicit RecursiveTablePotential(std::istream& istr);
  virtual ~RecursiveTablePotential();

  //@}
 private:
  std::vector<std::vector<double> > inner_sq_;
  std::vector<std::vector<double> > cutoff_sq_;
  std::vector<int> site_types_;
  std::vector<std::string> site_type_names_;
  std::vector<int> t2index_;
  std::vector<std::vector<std::unique_ptr<RecursiveTable1D> > > energy_table_;
  std::string mayer_training_file_;
  double hard_limit_u_, beta_, min_criteria_;
  int size_;

  void build_table_(const double lower, const double upper, const std::vector<std::vector<double> >& data, RecursiveTable1D * tab) const;
  double r2z_(const double r, const double lower, const double upper) const {
    return (r - lower)/(upper - lower); }
  double z2r_(const double z, const double lower, const double upper) const {
    return lower + z*(upper - lower); }
  int analyze_table_(const double lower, const double upper, const std::vector<std::vector<double> >& data, const Table1D& table, const double beta, const std::string& filename, double * criteria);
};

}  // namespace feasst

#endif  // FEASST_MODELS_RECURSIVE_TABLE_POTENTIAL_H_
