
#ifndef FEASST_ANISO_BUILD_RECURSIVE_TABLE_H_
#define FEASST_ANISO_BUILD_RECURSIVE_TABLE_H_

#include <memory>
#include <string>
#include <vector>
#include <cstdint>
#include "monte_carlo/include/action.h"

namespace feasst {

class RecursiveTable1D;
class RecursiveTable2D;
class RecursiveTable5D;
class System;
class Table1D;

/**
  The RecursiveTable is generated by comparing with the output of
  MayerSampling::training_file.
  This example assumes single-site isotropic interactions, in which case the
  training file simply contains a list of squared distances and energy.

  To begin, an inner cutoff distance is obtained by finding the lowest distance
  at which the energy is less than the given parameter "hard_limit_u."
  The outer cutoff is can be set manually or automatically generated.

  A 1D RecursiveTable of given size is generated by linearly
  interpolating between the closest data points.

  Then all of the data is evaluated against the following criteria in order to
  iteratively insert nested tables inside the elements of the first table,

  \f$r^2|\exp(-\beta U) - \exp(-\beta U_{table})|\f$,

  where \f$U\f$ is from the data points, \f$U_{table}\f$ is linearly
  interpolated, and \f$\beta\f$ is a given parameter which determines the
  relative emphasis on accurately fitting the highest energies.
  This functional form was inspired by the 3d integration of a Mayer funciton
  to include the \f$r^2\f$ Jacobian term to appropriately weight larger
  distances.
  In addition, increased beta (low temperature) weighs the low energy
  configurations more.
  This iterative process continues until the criteria of all data points are
  less than the given "min_criteria."

  As currently implemented, the RecursiveTable has a maximum depth of one
  recursion.
  This means that "min_criteria" can be set too low and never achieved,
  at which point the user will be presented with an error.
  This happens if a data point inside of an element that has already had a
  RecursiveTable inserted is still above the "min_criteria."
 */
class BuildRecursiveTable : public Action {
 public:
  //@{
  /** @name Arguments
    - mayer_training_file: input file, output by MayerSampling::training_file.
    - cutoff: cutoff distance. If -1, find automatically (default: -1).
    - output_file: write RecursiveTablePotential checkpoint file.
    - verbose_file: output file for more fitting information.
    - hard_limit_u: determines the inner cutoff distance (default: 100).
    - size: the size of each of the RecursiveTable s (default: 5).
    - num_orientations_per_pi: angular size of each of the RecursiveTable s (default: 5).
    - beta: parameter which weights low energy configurations (default: 1).
    - min_criteria: iterative target minimum criteria (default: 0.03).
   */
  explicit BuildRecursiveTable(argtype args = argtype());
  explicit BuildRecursiveTable(argtype * args);

  //@}
  /** @name Public Functions
   */
  //@{

  void run(MonteCarlo * mc) override;
  std::shared_ptr<Action> create(std::istream& istr) const override {
    return std::make_shared<BuildRecursiveTable>(istr); }
  std::shared_ptr<Action> create(argtype * args) const override {
    return std::make_shared<BuildRecursiveTable>(args); }
  void serialize(std::ostream& ostr) const override;
  explicit BuildRecursiveTable(std::istream& istr);
  virtual ~BuildRecursiveTable();

  //@}
 private:
  std::string mayer_training_file_, verbose_file_, output_file_;
  double hard_limit_u_, beta_, min_criteria_, cutoff_;
  int size_, num_orientations_per_pi_;

  std::string verbose_name_(const int iteration) const;
  void build_table_(const std::vector<std::vector<double> >& bounds, const std::vector<std::vector<double> >& data, RecursiveTable1D * tab, MonteCarlo * mc) const;
  int analyze_table_(const double lower, const double upper, const std::vector<std::vector<double> >& data, const Table1D& table, const double beta, const std::string& filename, double * criteria);
  RecursiveTable5D build_contact_(const std::vector<std::vector<double> >& bounds, const std::string& verbf, System * system);
  RecursiveTable2D build_2dcontact_(const std::vector<std::vector<double> >& bounds, const std::string& verbf, System * system);
  void analyze_contact_(const std::vector<std::vector<double> >& data,
    const RecursiveTable5D& contact, const RecursiveTable2D& contact2d, const std::vector<std::vector<double> >& abnd, const std::string& verbf,
    double * criteria, std::vector<int> * max_bins, std::vector<std::vector<double> > * new_bounds,
    std::vector<double> * max_s) const;
};

}  // namespace feasst

#endif  // FEASST_ANISO_BUILD_RECURSIVE_TABLE_H_
