
#ifndef FEASST_ANISO_BUILD_RECURSIVE_TABLE_H_
#define FEASST_ANISO_BUILD_RECURSIVE_TABLE_H_

#include <memory>
#include <string>
#include <vector>
#include <cstdint>
#include "monte_carlo/include/action.h"

namespace feasst {

class RecursiveTable1D;
class RecursiveTable2D;
class RecursiveTable3D;
class RecursiveTable5D;
class RecursiveTable6D;
class System;
class Table1D;

/**
  This class is experimental.
  The RecursiveTable is generated by comparing with the output of
  MayerSampling::training_file.
  This example assumes single-site isotropic interactions, in which case the
  training file simply contains a list of squared distances and energy.

  To begin, an inner cutoff distance is obtained by finding the lowest distance
  at which the energy is less than the given parameter "hard_limit_u."
  The outer cutoff is can be set manually or automatically generated.

  A 1D RecursiveTable of given size is generated by linearly
  interpolating between the closest data points.

  Then all of the data is evaluated against the following criteria in order to
  iteratively insert nested tables inside the elements of the first table,

  \f$r^2|\exp(-\beta U) - \exp(-\beta U_{table})|\f$,

  where \f$U\f$ is from the data points, \f$U_{table}\f$ is linearly
  interpolated, and \f$\beta\f$ is a given parameter which determines the
  relative emphasis on accurately fitting the highest energies.
  This functional form was inspired by the 3d integration of a Mayer funciton
  to include the \f$r^2\f$ Jacobian term to appropriately weight larger
  distances.
  In addition, increased beta (low temperature) weighs the low energy
  configurations more.
  This iterative process continues until the criteria of all data points are
  less than the given "min_criteria."

  As currently implemented, the RecursiveTable has a maximum depth of one
  recursion.
  This means that "min_criteria" can be set too low and never achieved,
  at which point the user will be presented with an error.
  This happens if a data point inside of an element that has already had a
  RecursiveTable inserted is still above the "min_criteria."
 */
class BuildRecursiveTable : public Action {
 public:
  //@{
  /** @name Arguments
    - mayer_training_file: input file, output by MayerSampling::training_file.
    - cutoff: cutoff distance. If -1, find automatically (default: -1).
    - output_file: write RecursiveTablePotential checkpoint file.
    - verbose_file: output file for more fitting information (default: empty).
    - extra_verbose: If true, output even more more (default: false).
    - hard_limit_u: determines the inner cutoff distance (default: 100).
    - num_orientations_per_pi: angular size of each of the RecursiveTable s (default: 5).
    - beta: parameter which weights low energy configurations (default: 1).
      Only affects energy tables, so not required for contact_only (see below).
    - num_z: the number of distances for each of the RecursiveTable s (default: 5).
      Only affects energy tables, so not required for contact_only (see below).
    - min_criteria: iterative target minimum criteria (default: 0.03).
    - min_criteria_energy: iterative target minimum criteria for energy. (default: 0).
      If negative, set to min_criteria above.
    - contact_only: If true, only consider hard contact (default: false).
   */
  explicit BuildRecursiveTable(argtype args = argtype());
  explicit BuildRecursiveTable(argtype * args);

  //@}
  /** @name Public Functions
   */
  //@{

  void run(MonteCarlo * mc) override;
  std::shared_ptr<Action> create(std::istream& istr) const override {
    return std::make_shared<BuildRecursiveTable>(istr); }
  std::shared_ptr<Action> create(argtype * args) const override {
    return std::make_shared<BuildRecursiveTable>(args); }
  void serialize(std::ostream& ostr) const override;
  explicit BuildRecursiveTable(std::istream& istr);
  virtual ~BuildRecursiveTable();

  //@}
 private:
  std::string mayer_training_file_, verbose_file_, output_file_;
  double hard_limit_u_, beta_, min_criteria_, min_criteria_energy_, cutoff_;
  int num_z_, num_orientations_per_pi_;
  bool contact_only_, extra_verbose_;

  std::string verbose_name_(const int iteration) const;
  void build_table_(const std::vector<std::vector<double> >& bounds, const std::vector<std::vector<double> >& data, RecursiveTable1D * tab, MonteCarlo * mc) const;
  int analyze_table_(const double lower, const double upper, const std::vector<std::vector<double> >& data, const Table1D& table, const double beta, const std::string& filename, double * criteria);
  RecursiveTable5D build_contact_(const std::vector<std::vector<double> >& bounds, const std::string& verbf, System * system, const bool cutoff = false);
  RecursiveTable2D build_2dcontact_(const std::vector<std::vector<double> >& bounds, const std::string& verbf, System * system, const bool cutoff = false);
  RecursiveTable1D build_1dcontact_(const std::vector<std::vector<double> >& bounds, const std::string& verbf, System * system, const bool cutoff = false);
  RecursiveTable3D build_3denergy_(const std::vector<std::vector<double> >& bounds, const std::vector<double>& zbnds, const std::string& verbf, const RecursiveTable2D& contact, const RecursiveTable2D& cutoff, System * system);
  RecursiveTable2D build_2denergy_(const std::vector<std::vector<double> >& bounds, const std::vector<double>& zbnds, const std::string& verbf, const RecursiveTable1D& contact, const RecursiveTable1D& cutoff, System * system);
  RecursiveTable6D build_energy_(const std::vector<std::vector<double> >& bounds, const std::vector<double>& zbnds, const std::string& verbf, const RecursiveTable5D& contact, const RecursiveTable5D& cutoff, System * system);
  void analyze_contact_(const std::vector<std::vector<double> >& data,
    const RecursiveTable5D& contact, const RecursiveTable2D& contact2d, const RecursiveTable1D& contact1d,
    const std::vector<std::vector<double> >& abnd, const int dimen, const std::string& verbf, const std::vector<std::vector<int> >& rbins,
    double * criteria, std::vector<int> * max_bins, std::vector<std::vector<double> > * new_bounds,
    std::vector<double> * max_s, const bool cutoff = false) const;
  void analyze_energy_(const std::vector<std::vector<double> >& data,
    const RecursiveTable6D& energy, const RecursiveTable3D& energy3d, const RecursiveTable2D& energy2d,
    const RecursiveTable5D& contact, const RecursiveTable2D& contact2d, const RecursiveTable1D& contact1d,
    const RecursiveTable5D& cutoff, const RecursiveTable2D& cutoff2d, const RecursiveTable1D& cutoff1d,
    const std::vector<std::vector<double> >& abnd, const std::string& verbf,
    const std::vector<std::vector<int> >& rbins, const bool is_2d,
    double * criteria, std::vector<int> * max_bins, std::vector<std::vector<double> > * new_bounds,
    std::vector<double> * new_zbnds,
    std::vector<double> * max_s) const;
  bool is_iso_(const bool is_2d, const int bsize) const;
};

}  // namespace feasst

#endif  // FEASST_ANISO_BUILD_RECURSIVE_TABLE_H_
