
#ifndef FEASST_ANISO_BUILD_RECURSIVE_TABLE_H_
#define FEASST_ANISO_BUILD_RECURSIVE_TABLE_H_

#include <memory>
#include <string>
#include <vector>
#include <cstdint>
#include "monte_carlo/include/action.h"
#include "aniso/include/rotator.h"

namespace feasst {

class ModelRecursiveTable;
class RecursiveTable;
class RecursiveTable1D;
class RecursiveTable2D;
class RecursiveTable3D;
class RecursiveTable5D;
class RecursiveTable6D;
class RTable;
class System;
class Table1D;

typedef std::pair<std::vector<int>, double> rbin;

/*
 DEV notes

implement a new method where global contact and cutoff scales z instead, and energy is the only table. This enables convex shapes and allows centering for lowest cutoff

Enable buildrecursive within Mayer itself? Make a new derived Mayer learning class which can be parallelized? Probably not worth it .., but would avoid large file output. Would need to build base first.

Should be agnostic to sampling algorithm, e.g., 1 fluid fh works as well

If enable serial combines to work in parallel, script, only run on first proc, there's still no way to make it wait... Until we had wait for file

WriteFileAndCheck
Wait UntilFileExists=
 */

/**
  This class is experimental.
  The RecursiveTable is generated by comparing with the output of
  MayerSampling::training_file.
  This example assumes single-site isotropic interactions, in which case the
  training file simply contains a list of squared distances and energy.

  To begin, an inner cutoff distance is obtained by finding the lowest distance
  at which the energy is less than the given parameter "hard_limit_u."
  The outer cutoff is can be set manually or automatically generated.

  A 1D RecursiveTable of given size is generated by linearly
  interpolating between the closest data points.

  Then all of the data is evaluated against the following criteria in order to
  iteratively insert nested tables inside the elements of the first table,

  \f$r^2|\exp(-\beta U) - \exp(-\beta U_{table})|\f$,

  where \f$U\f$ is from the data points, \f$U_{table}\f$ is linearly
  interpolated, and \f$\beta\f$ is a given parameter which determines the
  relative emphasis on accurately fitting the highest energies.
  This functional form was inspired by the 3d integration of a Mayer funciton
  to include the \f$r^2\f$ Jacobian term to appropriately weight larger
  distances.
  In addition, increased beta (low temperature) weighs the low energy
  configurations more.
  This iterative process continues until the criteria of all data points are
  less than the given "min_criteria."

  As currently implemented, the RecursiveTable has a maximum depth of one
  recursion.
  This means that "min_criteria" can be set too low and never achieved,
  at which point the user will be presented with an error.
  This happens if a data point inside of an element that has already had a
  RecursiveTable inserted is still above the "min_criteria."

  Parallel algorithm:
  1. In parallel, run Mayer-sampling simulations to generate training data
  2. In parallel, build base table for rh (if applicable, also rc and U)
     - aggregate of all training data is required because build automatically
       determines global cutoff and contact based on all data.
  3. In serial, combine tables into one base table.
  4. In parallel, read Mayer trainining file line by line to determine which
     base table elements are to be nested.
     - optionally, stop at certain max percentage?
     - optionally, sort nested by deviation from criteria
  5. In serial (post-process), union set of elements to be nested from each processor
     to avoid duplicates
  6. In parallel, build nested tables.
  7. In serial (post-process) combine into one nested table.
     - optionally, check that max deviation from criteria does not occur in a
       nested element, or else the criteria was too strict and may have resulted
       in inefficiently nesting too many.

  Multiple script HPC example allows submission of many single core jobs by
  completing one stage at a time:
  - (before stages): MayerSampling (step 1, postprocess combine data)
  - "base" stage: (step 2, postprocess step 3)
  - "train" stage: (step 4, postprocess step 5)
  - "build" stage: (step 6, postprocess step 7)
    - optionally, Prepare during Mayer to avoid large data files, but this
      requires deciding table parameters. Changing parameters would require
      rerunning the MayerSampling portion.
 */
class BuildRecursiveTable : public Action {
 public:
  //@{
  /** @name Arguments
    - stage: if all (default), run all stages with limited-efficiency OMP
      parallelization. If base, train, build_contact, build_cutoff,
      build_energy, only complete the stage described above (enables processor-
      based parallelization).
      If base, automatically sets assume_all_unique to true and min_criteria to
      NEAR_INFINITY.
      If build*, automatically sets assume_all_unique to true.
    - mayer_training_file: input file, output by MayerSampling::training_file.
    - cutoff: cutoff distance. If -1, find automatically (default: -1).
    - output_file: write RecursiveTablePotential checkpoint file.
    - verbose_file: output file for more fitting information (default: empty).
    - extra_verbose: If true, output even more more (default: false).
    - hard_limit_u: determines the inner cutoff distance (default: 100).
    - num_orientations_per_pi: angular size of each of the RecursiveTable s (default: 5).
    - beta: parameter which weights low energy configurations (default: 1).
      Only affects energy tables, so not required for contact_only (see below).
    - contact_only: If true, only consider hard contact (default: false).
    - energy_only: If true, only consider energy (default: false).
    - input_recursive_table: optionally, if energy_only, input existing contact
      and cutoff by providing the file name of the
      RecursiveTable VisitModelInnerTable.
    - num_z: the number of distances for each of the RecursiveTable s (default: 5).
      Only affects energy tables, so not required for contact_only (see below).
    - min_criteria: iterative target minimum criteria (default: 0.03).
    - min_criteria_energy: iterative target minimum criteria for energy. (default: 0).
      If <= 0, set to min_criteria above.
    - assume_all_unique: if true, do not search for uniqueness (default: false).
    - num_processors: number of processors to parallelize (default: 1).
    - processor: index of current processor [0, num_processors-1] (default: 0).
    - base_table_file: optional file name output from BuildBaseTable.
    - trained_file: optionally, if provided with base_table_file, generate the
      recursive tables without requiring criteria/beta/hard_limit_u, etc.
   */
  explicit BuildRecursiveTable(argtype args = argtype());
  explicit BuildRecursiveTable(argtype * args);

  //@}
  /** @name Public Functions
   */
  //@{

  void base(const bool is_energy, MonteCarlo * mc);
  void train(const bool is_cutoff, const bool is_energy, MonteCarlo * mc);
  void build(const bool is_cutoff, const bool is_energy, MonteCarlo * mc);
  void run(MonteCarlo * mc) override;
  std::shared_ptr<Action> create(std::istream& istr) const override {
    return std::make_shared<BuildRecursiveTable>(istr); }
  std::shared_ptr<Action> create(argtype * args) const override {
    return std::make_shared<BuildRecursiveTable>(args); }
  void serialize(std::ostream& ostr) const override;
  explicit BuildRecursiveTable(std::istream& istr);
  virtual ~BuildRecursiveTable();

  //@}
 protected:
  void serialize_build_recursive_table_(std::ostream& ostr) const;

 private:
  std::string mayer_training_file_, verbose_file_, output_file_, input_recursive_table_;
  double hard_limit_u_, beta_, min_criteria_, min_criteria_energy_, cutoff_;
  int num_z_, num_orientations_per_pi_, processor_, num_processors_;
  bool contact_only_, energy_only_, extra_verbose_;
  std::string assume_all_unique_;
  std::string base_table_file_, trained_file_, stage_;

  std::string verbose_name_(const int iteration) const;
  void build_table_(const std::vector<std::vector<double> >& bounds, RecursiveTable1D * tab, MonteCarlo * mc) const;
  int analyze_table_(const double lower, const double upper, const std::vector<std::vector<double> >& data, const Table1D& table, const double beta, const std::string& filename, double * criteria);
  RecursiveTable5D build_contact_(const std::vector<std::vector<double> >& bounds, const std::string& verbf, System * system, std::vector<System> * systems, const bool cutoff = false);
  RecursiveTable2D build_2dcontact_(const std::vector<std::vector<double> >& bounds, const std::string& verbf, System * system, std::vector<System> * systems, const bool cutoff = false);
  RecursiveTable1D build_1dcontact_(const std::vector<std::vector<double> >& bounds, const std::string& verbf, System * system, std::vector<System> * systems, const bool cutoff = false);
  RecursiveTable3D build_3denergy_(const std::vector<std::vector<double> >& bounds, const std::vector<double>& zbnds, const std::string& verbf, const RecursiveTable2D& contact, const RecursiveTable2D& cutoff, System * system, std::vector<System> * systems);
  RecursiveTable2D build_2denergy_(const std::vector<std::vector<double> >& bounds, const std::vector<double>& zbnds, const std::string& verbf, const RecursiveTable1D& contact, const RecursiveTable1D& cutoff, System * system, std::vector<System> * systems);
  RecursiveTable6D build_energy_(const std::vector<std::vector<double> >& bounds, const std::vector<double>& zbnds, const std::string& verbf, const RecursiveTable5D& contact, const RecursiveTable5D& cutoff, System * system, std::vector<System> * systems);
  void analyze_contact_(const std::vector<std::vector<double> >& data,
    const RecursiveTable5D& contact, const RecursiveTable2D& contact2d, const RecursiveTable1D& contact1d,
    const std::vector<std::vector<double> >& abnd, const int dimen, const std::string& verbf, const std::vector<std::vector<int> >& rbins,
    double * criteria, std::vector<int> * max_bins, std::vector<std::vector<double> > * new_bounds,
    std::vector<double> * max_s, const bool cutoff = false) const;
  void analyze_energy_(const std::vector<std::vector<double> >& data,
    const RecursiveTable6D& energy, const RecursiveTable3D& energy3d, const RecursiveTable2D& energy2d,
    const RecursiveTable5D& contact, const RecursiveTable2D& contact2d, const RecursiveTable1D& contact1d,
    const RecursiveTable5D& cutoff, const RecursiveTable2D& cutoff2d, const RecursiveTable1D& cutoff1d,
    const std::vector<std::vector<double> >& abnd, const std::string& verbf,
    const std::vector<std::vector<int> >& rbins, const bool is_2d,
    double * criteria, std::vector<int> * max_bins, std::vector<std::vector<double> > * new_bounds,
    std::vector<double> * new_zbnds,
    std::vector<double> * max_s) const;
  bool is_iso_(const bool is_2d, const int bsize) const;
  Rotator gen_rotator_(const std::vector<std::vector<double> >& bounds, System * system);
  void gen_rotators_(const std::vector<std::vector<double> >& bounds, std::vector<System> * systems, int * num_threads, std::vector<Rotator> * rotators);
  Rotator * get_rotator_(const int ithread, Rotator * rotator, std::vector<Rotator> * rotators);
  System * get_system_(const int ithread, System * system, std::vector<System> * systems);
  int get_num_threads_();
  void get_table_ptrs_(const bool is_cutoff, RecursiveTable * recur, RTable *& contact, RTable *& cutoff, RTable *& energy, RTable *& table) const;
  void base_iso_iso_(std::ostream& ostr, MonteCarlo * mc);

  // temporary variables if stage == all, not currently checkpointed
  std::shared_ptr<ModelRecursiveTable> base_mrt_, mrt_;
  std::shared_ptr<RecursiveTable> base_rt_, rt_;
  std::shared_ptr<std::vector<rbin> > rbins_;
};

/// Sort rbins by criteria and print them to file.
void sort_and_print(std::vector<rbin> * rbins, const std::string& filename);

/// Obtain rbins from file in the same format as above, optionally in parallel
std::vector<rbin> read_rbins(const std::string& filename,
  const int processor = 0, const int num_processors = 1);

}  // namespace feasst

#endif  // FEASST_ANISO_BUILD_RECURSIVE_TABLE_H_
